spring.datasource.url=jdbc:mysql://localhost:3306/conciliadb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Use the schema.sql file to create the database structure
spring.sql.init.mode=never
